# This is a basic workflow to help you get started with Actions

name: FuncionalTesting

# Controls when the workflow will run
on: [push]

jobs:
  # This workflow contains a single job called "build"
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Descargando
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Cypress.io
      - uses: cypress-io/github-action@v2.9.7     
